let classInfo = [
  {
    id: 1,
    name: "Optionals",
    abbreviation: "O",
    displayName: "Optionals",
    color: "#02dddd",
  },
  {
    id: 2,
    name: "Level 3 Team",
    abbreviation: "3T",
    displayName: "3 Team",
    color: "#02dddd",
  },
  {
    id: 3,
    name: "Level 4 Team",
    abbreviation: "4T",
    displayName: "4 Team",
    color: "#02dddd",
  },
  {
    id: 4,
    name: "Pre-Team",
    abbreviation: "PT",
    displayName: "Pre-Team",
    color: "#61eec1",
  },
  {
    id: 5,
    name: "Xcel Bronze",
    abbreviation: "XB",
    displayName: "Xcel Bronze",
    color: "#7cffeb",
  },
  {
    id: 6,
    name: "Xcel Silver",
    abbreviation: "XS",
    displayName: "Xcel Silver",
    color: "#7cffeb",
  },
  {
    id: 7,
    name: "Xcel Gold",
    abbreviation: "XG",
    displayName: "Xcel Gold",
    color: "#7cffeb",
  },
  {
    id: 8,
    name: "Xcel Platinum",
    abbreviation: "XP",
    displayName: "Xcel Plat",
    color: "#7cffeb",
  },
  {
    id: 9,
    name: "Rec Level 1",
    abbreviation: "L1",
    displayName: "Rec 1",
    color: "#ff7df3",
  },
  {
    id: 10,
    name: "Rec Level 2",
    abbreviation: "L2",
    displayName: "Rec 2",
    color: "#cc66ff",
  },
  {
    id: 11,
    name: "Rec Level 3",
    abbreviation: "L3",
    displayName: "Rec 3",
    color: "#9999ff",
  },
  {
    id: 12,
    name: "Tiny Tots",
    abbreviation: "TT",
    displayName: "Tiny Tots",
    color: "#69c5ff",
  },
  {
    id: 13,
    name: "Mini Tots",
    abbreviation: "MT",
    displayName: "Mini Tots",
    color: "#b4d6ff",
  },
  {
    id: 14,
    name: "Kinder Tots",
    abbreviation: "KT",
    displayName: "Kinder Tots",
    color: "#a9e9ff",
  },
  {
    id: 15,
    name: "Hot Shots",
    abbreviation: "HS",
    displayName: "Hot Shots",
    color: "#b6ffe5",
  },
  {
    id: 16,
    name: "Ninja Preschool",
    abbreviation: "NPre",
    displayName: "Ninja Pre",
    color: "#ff9f87",
  },
  {
    id: 17,
    name: "Ninja Primary",
    abbreviation: "NP",
    displayName: "Ninja P",
    color: "#ff7e64",
  },
  {
    id: 18,
    name: "Ninja Junior",
    abbreviation: "NJ",
    displayName: "Ninja J",
    color: "#ffb764",
  },
  {
    id: 19,
    name: "Ninja Senior",
    abbreviation: "NS",
    displayName: "Ninja S",
    color: "#ffd96e",
  },
  {
    id: 20,
    name: "Competitive Ninja",
    abbreviation: "CN",
    displayName: "C Ninja",
    color: "#f0c841",
  },
  {
    id: 21,
    name: "Tumbling",
    abbreviation: "T",
    displayName: "Tumbling",
    color: "#9bff9b",
  },
  {
    id: 22,
    name: "Advanced Tumbling",
    abbreviation: "AT",
    displayName: "Adv Tumbling",
    color: "#01ce01",
  },
  {
    id: 23,
    name: "Cheer Preschool",
    abbreviation: "CP",
    displayName: "Cheer Pre",
    color: "#f4c2e5",
  },
  {
    id: 24,
    name: "Cheer Kinder",
    abbreviation: "CK",
    displayName: "Cheer Kinder",
    color: "#f474d6",
  },
  {
    id: 25,
    name: "Cheer Rec",
    abbreviation: "CR",
    displayName: "Cheer Rec",
    color: "#ff84be",
  },
  {
    id: 26,
    name: "Physical Activity",
    abbreviation: "PA",
    displayName: "PA",
    color: "#74ff3b",
  },
  {
    id: 27,
    name: "Ballet",
    abbreviation: "B",
    displayName: "Ballet",
    color: "#ffadec",
  },
  {
    id: 28,
    name: "Rec Level 1 Mini",
    abbreviation: "L1M",
    displayName: "Rec 1 Mini",
    color: "#a64d79",
  },
  {
    id: 29,
    name: "Accelerated Summer",
    abbreviation: "AS",
    displayName: "Acc Summer",
    color: "#ffd966",
  },
  {
    id: 30,
    name: "Cleaning",
    abbreviation: "C",
    displayName: "Cleaning",
    color: "#00ffff",
  },
]

export default classInfo;
